image: ruby:2.3

test:
  stage: test
  script:
  - gem install jekyll
  - jekyll build -d test
  - npm install react-share --save
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - gem install jekyll
  - jekyll build -d public
  - npm install react-share --save
  artifacts:
    paths:
    - public
  only:
  - master


