image: ruby:2.3

test:
  stage: test
  script:
  - gem install jekyll
  - jekyll build -d test
  - gem install social-share-button
  - bundle install
  - rails generate social_share_button:install
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - gem install jekyll
  - jekyll build -d public
  - gem install social-share-button
  - bundle install
  - rails generate social_share_button:install
  artifacts:
    paths:
    - public
  only:
  - master


